/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PresentationsRouteRouteImport } from './routes/presentations/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PresentationsIndexRouteImport } from './routes/presentations/index'
import { Route as PresentationsTopicRouteImport } from './routes/presentations/$topic'

const PresentationsRouteRoute = PresentationsRouteRouteImport.update({
  id: '/presentations',
  path: '/presentations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsIndexRoute = PresentationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PresentationsRouteRoute,
} as any)
const PresentationsTopicRoute = PresentationsTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => PresentationsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/presentations': typeof PresentationsRouteRouteWithChildren
  '/presentations/$topic': typeof PresentationsTopicRoute
  '/presentations/': typeof PresentationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/presentations/$topic': typeof PresentationsTopicRoute
  '/presentations': typeof PresentationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/presentations': typeof PresentationsRouteRouteWithChildren
  '/presentations/$topic': typeof PresentationsTopicRoute
  '/presentations/': typeof PresentationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/presentations' | '/presentations/$topic' | '/presentations/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/presentations/$topic' | '/presentations'
  id:
    | '__root__'
    | '/'
    | '/presentations'
    | '/presentations/$topic'
    | '/presentations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PresentationsRouteRoute: typeof PresentationsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/presentations': {
      id: '/presentations'
      path: '/presentations'
      fullPath: '/presentations'
      preLoaderRoute: typeof PresentationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations/': {
      id: '/presentations/'
      path: '/'
      fullPath: '/presentations/'
      preLoaderRoute: typeof PresentationsIndexRouteImport
      parentRoute: typeof PresentationsRouteRoute
    }
    '/presentations/$topic': {
      id: '/presentations/$topic'
      path: '/$topic'
      fullPath: '/presentations/$topic'
      preLoaderRoute: typeof PresentationsTopicRouteImport
      parentRoute: typeof PresentationsRouteRoute
    }
  }
}

interface PresentationsRouteRouteChildren {
  PresentationsTopicRoute: typeof PresentationsTopicRoute
  PresentationsIndexRoute: typeof PresentationsIndexRoute
}

const PresentationsRouteRouteChildren: PresentationsRouteRouteChildren = {
  PresentationsTopicRoute: PresentationsTopicRoute,
  PresentationsIndexRoute: PresentationsIndexRoute,
}

const PresentationsRouteRouteWithChildren =
  PresentationsRouteRoute._addFileChildren(PresentationsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PresentationsRouteRoute: PresentationsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
